### PR TITLE
Removes trailing "/" from ROOT_URL

### PR DESCRIPTION
**Pull request by zvictor**
Please check http://docs.meteor.com/#/full/meteor_absoluteurl

### CODE REVIEW

**Comment by zvictor** [comment]
Actually the documentation is talking about the argument to the function that generate URLs. It does not apply to the ROOT_URL itself. However, I still believe that not having "/" at the end is the right form.

**Comment by SamHatoum** [comment]
I think that's how Meteor outputs it, and that's how all the old xolvio:cucumber specs worked (they assumed the ROOT_URL had a trailing slash).

If you use `url.resolve(process.env.ROOT_URL, '/some/path')`, then it shouldn't affect you either way

**Comment by zvictor** [comment]
I couldn't find a "right way" to define ROOT_URL in the docs, so I checked the source code of Meteor.
All the examples are missing the trailing slash:
- https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/packages/meteor/url_common.js#L8
- https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/tools/tests/cordova-hcp.js#L38
- https://github.com/meteor/meteor/blob/f7b2735d2320eecafe478f3e4dd77ccaab848194/tools/isobuild/bundler.js#L1983

However, Meteor accepts all sort of well formed URLs, as mentioned in this [commit message](https://github.com/meteor/meteor/commit/26feea9275bbba0d7b3fceedd10298e5deb81f08).

That said, you are free to choose whatever format you prefer.

The only reason why it would be good to have a standard way to define the variable is to avoid future need of refactoring our tests in case this variable changes. Consider the following example.

``` js
var relative = client.getAttribute(selector, 'src').replace(process.env.ROOT_URL, '');
expect(relative).toEqual(someUrl);
```

`relative` might have a leading slash or not, depending on how you defined ROOT_URL.

**Comment by SamHatoum** [comment]
I'm convinced :)

**Pull request merged**
