### PR TITLE
Add debug mode

### PR DESCRIPTION
**Pull request by zvictor**
### Debug mode

screen shot 2016-06-14 at 16 57 31
### Usage
- `npm start -- --debug`
- `npm start -- --jasmine --debug`
### Tip

As you will be debugging and constantly changing/reloading your tests, you don't want to have meteor being rebuilt every time. Thus I recommend you to separate these processes by running the following two commands in separated terminals:
- `cd src && meteor run`
- `NO_METEOR=1 npm start -- --debug`

_Note 1: This PR is a continuation of the work started at #46_ 
_Note 2: Debug mode is very noisy and it will flood your console. Check xolvio/chimp#399 for details._

### CODE REVIEW

**Comment by SamHatoum** [comment]
@zvictor what do you think of making these scripts as a separate npm package, as suggested in #46?

**Comment by zvictor** [comment]
That would be great! Should I start it or do you have a WIP?

**Comment by zvictor** [comment]
Good, I will start it in the next weeks.

**Comment by SamHatoum** [comment]
Closing this as new version coming soon here:
https://github.com/xolvio/qualityfaster/tree/dev

**Pull request closed without merging**
